import pygame
pygame.init()

# SCREEN
SCREEN = pygame.display.set_mode((1280, 720))
WIDTH = pygame.display.get_surface().get_width()
HEIGHT = pygame.display.get_surface().get_height()

# FPS
CLOCK = pygame.time.Clock()
FPS = 60

# MOUSE (the start position of the mouse)
MOUSE_POS = pygame.mouse.get_pos()

#ANIMATIONS
FRAME_SPEED = 0.1

# SPEED
MOVE_SPEED = (WIDTH+HEIGHT)/400

# PLAYER
PLAYER_SIZE = [WIDTH/21.333, HEIGHT/12]
PLAYER_SCALE = 2
PLAYER_START_POSITION = [WIDTH/2, HEIGHT/1.2]
PLAYER_DAMAGE = 100
PLAYER_LIFE = 5
#       LIFE BAR
LIFE_BAR_POS_X = WIDTH/100
LIFE_BAR_POS_Y = HEIGHT/100
LIFE_BAR_SCALE = 1.1
LIFE_BAR_SIZE = [WIDTH/30, WIDTH/30]

# ENEMYES - TYPE 1
ENEMY_DAMAGE = 1
ENEMY_1_NORMAL_SPEED = MOVE_SPEED/1.4
ENEMY_1_SIZE = [WIDTH/25.6, HEIGHT/14.4]
ENEMY_1_SCALE = 2
ENEMY_1_RELOAD_TIME = 80
ENEMY_1_LIFE = 600
ENEMY_1_START_POSITION_Y = -ENEMY_1_SIZE[1]

# BOSS
BOSS_DAMAGE = 1
BOSS_NORMAL_SPEED = MOVE_SPEED/1.4
BOSS_SIZE = [WIDTH/25.6, HEIGHT/14.4]
BOSS_SCALE = 3
BOSS_RELOAD_TIME = 10
BOSS_LIFE = 10000
BOSS_START_POSITION = [WIDTH/2, -BOSS_SIZE[1]*2]

# BULLETS
BULLET_SIZE = [WIDTH/64, HEIGHT/36]
BULLET_SCALE = 2
BULLET_SPEED = -HEIGHT/103
BULLET_LIFE = 5000
#       BULLET - PLAYER
PLAYER_BULLET_CORRECTION_X = WIDTH/34
PLAYER_BULLET_CORRECTION_Y = HEIGHT/36
PLAYER_BULLET_CORRECTION_BALL = HEIGHT/12
PLAYER_BULLET_ULTIMATE_LIFE = 2000
#       BULLET - PLAYER - ULTIMATE
ULTIMATE_BULET_SIZE = [HEIGHT/15, HEIGHT]
ULTIMATE_CORRECTION_Y = ULTIMATE_BULET_SIZE[1]/0.96
ULTIMATE_CORRECTION_X = ULTIMATE_BULET_SIZE[0]/40
ULTIMATE_DAMAGE = 50

# SCORE
SCORE_POSITION = [WIDTH/100, HEIGHT/20*18.5]

# FONTS
FONT_BUTTONS = 'Fonts\8bitoperator\8bitoperator.ttf'
FONT_SCORE = 'Fonts\8bitoperator\8bitoperator.ttf'
SCORE_FONT_SIZE = int(WIDTH/35)

#ICON
ICON = pygame.image.load('Icon/Icon.png')